DEBUG=True
SECRET_KEY='dev_key_MYSECRETKEY'
CSRF_ENABLED=True
CSRF_SESSION_KEY='dev_key_MYCSRFKY'
RECAPTCHA_PUBLIC_KEY = 'MYRECAPTCHAPUBKEY'
RECAPTCHA_PRIVATE_KEY = 'MYRECAPTCHAPRIVKEY'
RECAPTCHA_USE_SSL = False
SEND_FILE_MAX_AGE_DEFAULT = 43200
